config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :picture, only: [:index, :new, :create, :edit, :update ,:destroy]
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

  root 'application#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :manage, :all           # allow superadmins to do anything
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  validates :comment, presence:true, length: {maximum: 140}
  validates :photo, presence: true

  belongs_to :user
  mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

  has_many :pictures
  mount_uploader :avatar, AvatarUploader #deviseの設定配下に追記

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
        name:     auth.extra.raw_info.name,
        provider: auth.provider,
        uid:      auth.uid,
        email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
        image_url:   auth.info.image,
        password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
        name:     auth.info.nickname,
        image_url: auth.info.image,
        provider: auth.provider,
        uid:      auth.uid,
        email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
        password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_actionで下で定義したメソッドを実行
  before_action :configure_permitted_parameters, if: :devise_controller?

  #変数PERMISSIBLE_ATTRIBUTESに配列[:name]を代入
  PERMISSIBLE_ATTRIBUTES = %i(name avatar avatar_cache)

  def index
    if user_signed_in?
      redirect_to picture_index_path
    else
      redirect_to new_user_session_path
    end
  end

  protected
    #deviseのストロングパラメーターにカラム追加するメソッドを定義
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end

end

app/controllers/picture_controller.rb
class PictureController < ApplicationController
  before_action :authenticate_user!
  before_action :set_picture, only:[ :edit, :update, :destroy]
  before_action :checkMatchUser, only:[:edit, :destroy]

  def index
    @pictures = Picture.order('updated_at DESC')
    @users = User.all
    @curUserId = current_user.id
  end

  def new
    if request.post?
      @picture = Picture.new(picture_params)
    else
      @picture = Picture.new
    end
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id

    if @picture.save
      redirect_to picture_index_path, notice: "投稿しました！"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to picture_index_path, notice: "更新しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @picture.destroy
    redirect_to picture_index_path, notice: "削除しました"
  end

  private
    def picture_params
      params.require(:picture).permit(:photo, :photo_cache, :comment)
    end

    def set_picture
      @picture = Picture.find(params[:id])
    end

    def checkMatchUser
      if current_user.id != @picture.user_id
        redirect_to picture_index_path
      end
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_img(user)
    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'def_profile.svg'
    end
    image_tag(img_url, alt: user.name, class:'regist__profile')
  end
end

app/helpers/picture_helper.rb
module PictureHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      picture_index_path
    elsif action_name == 'edit' || action_name == 'update'
      picture_path
    end
  end

  def profile_img(user)
    return image_tag(user.avatar, alt: user.name, class: 'regist__profile') if user.avatar?

    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'def_profile.svg'
    end
    image_tag(img_url, alt: user.name, class: 'regist__profile')
  end

end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>InstaMitai</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
<header class="header">
  <p class="header__logo">
    <a href="/"><img src="<%= asset_path "logo.svg" %>"></a>
  </p>
  <div class="header__tool">
    <%= link_to 'マイページ', edit_user_registration_path %>
    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete ,data: { confirm: 'ログアウトしますか？' }, class: '' %>

  </div>
</header>
<% end %>
<div class="page">
  <%= yield %>
</div>

<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/picture/_form.html.erb
<%= form_for(@picture, url:choose_new_or_edit) do |f| %>

  <% if @picture.errors.any? %>
    <div class="alert alert-danger">
      <p><%= @picture.errors.full_messages.count %>件のエラーがあります。</p>
      <ul>
        <% @picture.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel panel-default">
    <div class="panel-heading text-center">
      <% if isEdit %>
        <%= f.label :投稿の編集 %>
      <% else %>
        <%= f.label :写真投稿 %>
      <% end %>
    </div>
    <div class="panel-body">
      <div class="picture-preview">
        <%= image_tag(@picture.photo, alt: '', class: 'js-previewPhoto') %>
      </div>
      <%= f.file_field :photo , class:'picture__upLoader js-picUpLoadButton' %>
      <%= f.hidden_field :photo_cache %><!-- バリデーションエラー時の対策 -->
      <%= f.text_area :comment, rows: 6, class: 'form-control js-text-area' %>
      <p class="text-right"><span class="js-count-text">0</span> / 140</p>
      <div class="text-center">
        <%= f.submit :投稿, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

<p class="text-right">
  <%= link_to picture_index_path do %>
    <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>
    <span>一覧に戻る</span>
  <% end %>
</p>

app/views/picture/edit.html.erb
<section class="picture">
  <%= render 'form', { isEdit: true } %>
</section>

app/views/picture/index.html.erb
<% if notice %>
    <p class="pictureList__notice alert alert-success"><%= notice %></p>
<% else %>
<% end %>
<p class="text-center">
  <%= link_to '投稿する', new_picture_path, class: 'btn btn-default' %>
</p>

<div class="pictureList">
  <% @pictures.each do |picture| %>
    <div class="well">
      <div class="pictureList__user">
        <div class="pictureList__userThumb">
          <% user = @users.find(picture.user_id) %>
          <%= profile_img(user) %>
        </div>
        <p class="pictureList__userComment"><%= @users.find(picture.user_id).name %></p>
        <p class="text-right"><%= picture.updated_at.to_s(:default) %></p>
      </div>

      <div class="pictureList__photo">
        <%= image_tag(picture.photo, alt: '') %>
      </div>
      <p><%= picture.comment %></p>

      <% if picture.user_id == @curUserId %>
          <div class="text-right">
            <%= link_to edit_picture_path(picture.id) do %>
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
            <% end %>
            <%= link_to picture_path(picture.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } do %>
                <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            <% end %>
          </div>

      <% end %>
    </div>

  <% end %>
</div>

app/views/picture/new.html.erb
<section class="picture">
  <%= render 'form', { isEdit: false } %>
</section>